# Contenido

Estructuras de datos
- Array
- Matrices
- Operaciones

In [ ]:
import numpy as np #libreria básica de numpy

Creación de un vector con NumPy

In [ ]:
x = np.array([1, 2, 3])
print(x, type(x))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
x.shape

(3,)

In [ ]:
x[1]

2

**Crear una matriz**

In [ ]:
b = np.array([[1, 2],[3, 4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
b.shape

(2, 2)

In [ ]:
b[1,1]

4

## Extracción de Filas y Columnas

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a.shape

(3, 4)

In [ ]:
print(a[0,:])

[1 2 3 4]


In [ ]:
print(a[:,1])

[ 2  6 10]


In [ ]:
c = a[:,1:3]
print(c)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
c.shape

(3, 2)

## Operaciones con Matrices

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x+1)

[[2. 3.]
 [4. 5.]]


## Multiplicación de  Matrices

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [ ]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [ ]:
print(x*y)

[[ 5 12]
 [21 32]]
